// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqTRG6JEnt2WMhnCjYqBsX91t4HTFugQ',
    appId: '1:167468118462:web:112d3442079a96791109ef',
    messagingSenderId: '167468118462',
    projectId: 'lab3laststand',
    authDomain: 'lab3laststand.firebaseapp.com',
    storageBucket: 'lab3laststand.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-3HsBDP0cQp2LhrXbb4jxgD8oiIVeHE',
    appId: '1:167468118462:android:76d941597dbe01331109ef',
    messagingSenderId: '167468118462',
    projectId: 'lab3laststand',
    storageBucket: 'lab3laststand.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9za_Ehzq6-0MI9Jy6XLNiBUeuk2a120',
    appId: '1:167468118462:ios:6a01993705cd31341109ef',
    messagingSenderId: '167468118462',
    projectId: 'lab3laststand',
    storageBucket: 'lab3laststand.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9za_Ehzq6-0MI9Jy6XLNiBUeuk2a120',
    appId: '1:167468118462:ios:6a01993705cd31341109ef',
    messagingSenderId: '167468118462',
    projectId: 'lab3laststand',
    storageBucket: 'lab3laststand.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );
}
